### ISSUE TITLE
Nuevamente vuelven a ocurrir las redirecciones

### ISSUE THREAD

**Issue by fgallese** [narrowfail/UyList#2]
Buenas !

Toy viendo que nuevamente vuelven a ocurrir las redirecciones.

Le dediqué 5 minutos para verlo y me parece que el problema viene por la forma en que tamos bloqueando el epd_sw.js.

Veo que lo tenes como epd_sw.js$script,domain=www.elpais.com.uy pero actualmente veo que está siendo llamado con otros parámetros, tonces aparentemente no matchea en el bloqueo y por eso se ejecuta y nos mete la redirección.

Yo lo bloquié con un asesino epd_sw.js* y ahí anda, pero bueno... como decía, no le dediqué demasiado tiempo a pensarlo.

Salu2

**Comment by narrowfail** [comment]
Fabio,

muchas gracias por reportar el problema! Se modificó la regla para bloquear el script y se agregaron más dominios de la misma empresa. Espero tu confirmación para cerrar el Issue!

Saludos,
Guillermo

**Comment by narrowfail** [comment]
@fgallese, estuve haciendo pruebas y el problema parece haber quedado solucionado!
Gracias por reportarlo!

Saludos,
Guillermo
